name : Data Pipeline CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  pipeline_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.12'
      - name: Navigate To Project
        run: cd "Main Project/Project_P2_810100258_810100260_810199383"
      - name: Install Dependencies...
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install --only-binary :all: numpy  # Pre-compiled wheels
          pip install -r "Main Project/Project_P2_810100258_810100260_810199383/requirements.txt"
      - name: Run the Pipeline!
        run: python Main\ Project/Project_P2_810100258_810100260_810199383/pipeline.py
